import json

INPUT_FILE = "reports/final_prioritized_findings.json"
LLM_CONTEXT_FILE = "reports/llm_contexts.json"


def run(state):

    # Existing compact context for backward compatibility
    with open(INPUT_FILE) as f:
        findings = json.load(f)

    compact = []

    for finding in findings:

        compact.append({
            "finding_id": finding.get("finding_id"),
            "title": finding.get("title"),
            "tool": finding.get("tool"),
            "category": finding.get("category"),
            "severity": finding.get("severity"),
            "priority": finding.get("priority"),
            "file": finding.get("file"),
            "asset_type": finding.get("asset_type"),
            "reachability_score": finding.get(
                "reachability_score",
                0
            )
        })

    state["findings"] = compact

    # Prefer richer LLM context already generated by the pipeline
    if state.get("llm_contexts"):

        state["llm_contexts"] = state["llm_contexts"][:20]

    else:

        try:
            with open(LLM_CONTEXT_FILE) as f:
                llm_contexts = json.load(f)

            state["llm_contexts"] = llm_contexts[:20]

        except FileNotFoundError:

            print(
                "[ContextAgent] Warning: llm_contexts.json not found."
            )

            state["llm_contexts"] = []

    print(
        f"[ContextAgent] Loaded "
        f"{len(state['llm_contexts'])} LLM context packs"
    )

    print(
        f"[ContextAgent] Loaded "
        f"{len(compact)} findings"
    )

    return state